version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  
    container_name: analytica_django
    volumes:
      - .:/app
      - /app/__pycache__/
      - ./static:/app/static
      - ./media:/app/media
      - ./templates:/app/templates
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
    depends_on:
      - mysql
      # - redis
      # - celery

  mysql:
    image: mysql:8.0
    env_file:
      - .env 
    container_name: analytica_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # redis:
  #   image: redis:6.2
  #   container_name: analytica_redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

  # celery:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: >
  #     sh -c "dockerize -wait tcp://redis:6379 -timeout 60s &&
  #     celery -A StudentManagerProject worker --loglevel=info"
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #   env_file:
  #     - .env
  #   container_name: analytica_celery

volumes:
  mysql_data: