# Generated by Django 5.1.4 on 2025-01-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFile',
            fields=[
                ('file_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('file_name', models.CharField(default='New Document', max_length=40)),
                ('file', models.FileField(upload_to='analysis_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
