# Generated by Django 5.2.4 on 2025-07-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticaFiles',
            fields=[
                ('file_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('file_name', models.CharField(default='New Document', max_length=40)),
                ('file_path', models.FileField(upload_to='analysis_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'AnalyticaFiles',
            },
        ),
    ]
