# Generated by Django 5.1.7 on 2025-03-28 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytica_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analyticafiles',
            table='AnalyticaFiles',
        ),
    ]
