# Generated by Django 5.2.2 on 2025-06-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytica_app', '0002_alter_analyticafiles_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticafiles',
            old_name='file',
            new_name='file_path',
        ),
    ]
