# Generated by Django 5.1.4 on 2025-01-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytica_app', '0002_alter_analysisfile_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisfile',
            name='file_name',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
